#!/usr/bin/env python3
"""Fig 2 (lis_vs_greedy): LIS vs greedy on a REAL SEC interval from
GRB 221009A (Box A, stime=160124920, ds=1) containing a CRC-collision
ghost that triggers a greedy cascade.

Data source: plots/fig2_real_ghost_window.json
  (generated by scripts/extract_real_ghost_window.py from the raw 1B
   CCSDS packets — bypasses LIS, so rejected events are visible.)

Output: figures/f3_lis_vs_greedy.pdf in the paper repo.
"""
import json
import os
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pubstyle  # noqa: E402
pubstyle.apply()

with open("plots/fig2_real_ghost_window.json") as f:
    DATA = json.load(f)
events  = np.array(DATA["ef"], dtype=np.int64)
accept_greedy = np.array(DATA["accept_greedy"], dtype=bool)
accept_lis    = np.array(DATA["accept_lis"], dtype=bool)
GHOST_IDX     = int(DATA["ghost_local_idx"])
GHOST_FULL    = int(DATA["ghost_full_idx"])
CASCADE_FULL  = int(DATA["cascade_full"])
STIME         = int(DATA["stime"])
n = len(events)
ghost_val = int(events[GHOST_IDX])
ymax = max(int(events.max()) * 1.26, ghost_val * 1.26)


def draw_panel(ax, accept, title, mode):
    x = np.arange(n)
    bar_w = 0.78
    for i, v in enumerate(events):
        if i == GHOST_IDX:
            color = "#D6604D"; edge = "#7A1212"; hatch = ""; alpha = 0.95
        elif accept[i]:
            color = "#2166AC"; edge = "#0B3D6E"; hatch = ""; alpha = 0.92
        else:
            color = "#FBD9D2"; edge = "#A93226"; hatch = "////"; alpha = 0.95
        ax.bar(i, v, width=bar_w, color=color, edgecolor=edge,
               linewidth=1.0, hatch=hatch, alpha=alpha, zorder=3)

    # Ghost label: short pointer to the right of the bar
    ax.annotate(f"ghost\n$e \\approx 484\\!\\times\\!10^3$",
                xy=(GHOST_IDX + 0.5, ghost_val * 0.85),
                xytext=(GHOST_IDX + 2.5, ghost_val * 0.78),
                ha="left", va="center", fontsize=7, fontweight="bold",
                color="#7A1212",
                arrowprops=dict(arrowstyle="->", color="#7A1212", lw=1.0))

    if mode == "greedy":
        ax.axhline(ghost_val, color="#7A1212", ls="--", lw=1.4,
                   zorder=2, alpha=0.7)
        ax.text(n - 0.5, ghost_val + ymax * 0.012,
                "greedy threshold (raised by ghost)",
                fontsize=7, color="#7A1212", style="italic",
                va="bottom", ha="right", fontweight="bold")
        for i in range(n):
            if not accept[i] and i != GHOST_IDX:
                ax.text(i, events[i] + ymax * 0.018, "✗",
                        ha="center", va="bottom",
                        fontsize=8, color="#A93226", fontweight="bold")
        rej_idx = np.where(~accept & (np.arange(n) != GHOST_IDX))[0]
        if len(rej_idx):
            lo, hi = rej_idx.min(), rej_idx.max()
            ax.annotate("", xy=(hi + 0.4, ymax * 0.36),
                        xytext=(lo - 0.4, ymax * 0.36),
                        arrowprops=dict(arrowstyle="<->", color="#A93226",
                                        lw=1.6))
            ax.text((lo + hi) / 2, ymax * 0.38,
                    f"cascade: all {hi - lo + 1} rejected",
                    ha="center", va="bottom",
                    fontsize=7, color="#A93226", fontweight="bold")
    else:
        ax.annotate("isolated\n(length-1)",
                    xy=(GHOST_IDX - 0.3, ghost_val - ymax * 0.04),
                    xytext=(GHOST_IDX - 3.0, ghost_val * 0.85),
                    ha="right", va="center",
                    fontsize=7, color="#7A1212", fontweight="bold",
                    arrowprops=dict(arrowstyle="->", color="#7A1212",
                                    lw=1.2))
        acc_idx = np.where(accept & (np.arange(n) != GHOST_IDX))[0]
        post = acc_idx[acc_idx > GHOST_IDX]
        if len(post):
            lo, hi = post.min(), post.max()
            ax.annotate("", xy=(hi + 0.4, ymax * 0.36),
                        xytext=(lo - 0.4, ymax * 0.36),
                        arrowprops=dict(arrowstyle="<->", color="#0B3D6E",
                                        lw=1.6))
            ax.text((lo + hi) / 2, ymax * 0.38,
                    f"all {hi - lo + 1} accepted (no cascade)",
                    ha="center", va="bottom",
                    fontsize=7, color="#0B3D6E", fontweight="bold")

    ax.set_xticks(np.arange(0, n, 2))
    ax.set_xlim(-0.7, n - 0.3)
    ax.set_ylim(0, ymax)
    ax.set_xlabel("Event index in window (file order)")
    ax.set_ylabel(r"$e_i$  [2 $\mu$s ticks]")
    ax.text(0.02, 0.97, title, transform=ax.transAxes,
            fontweight="bold", va="top", ha="left")
    ax.grid(alpha=0.18, axis="y", zorder=1)
    ax.set_axisbelow(True)


def main():
    fig, (axT, axB) = plt.subplots(2, 1, figsize=(pubstyle.COL_W, 3.25),
                                   sharex=True,
                                   gridspec_kw={"hspace": 0.16})
    draw_panel(axT, accept_greedy, "Greedy", mode="greedy")
    draw_panel(axB, accept_lis, "LIS", mode="lis")
    axT.set_xlabel("")

    legend_elements = [
        Patch(facecolor="#2166AC", edgecolor="#0B3D6E", label="accepted"),
        Patch(facecolor="#FBD9D2", edgecolor="#A93226", hatch="////",
              label="rejected"),
        Patch(facecolor="#D6604D", edgecolor="#7A1212",
              label="ghost (CRC collision)"),
    ]
    fig.legend(handles=legend_elements, loc="upper center",
               ncol=3, frameon=False,
               bbox_to_anchor=(0.5, 1.00))

    fig.subplots_adjust(top=0.94, bottom=0.11, left=0.155, right=0.985)
    out_pdf = "/Users/skyair/Developer/ihep/paper-hxmt-saturation/figures/f3_lis_vs_greedy.pdf"
    out_png = "/Users/skyair/Developer/ihep/blink/plots/fig2_lis_vs_greedy_preview.png"
    plt.savefig(out_pdf)
    plt.savefig(out_png, dpi=150)
    plt.close()
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")
    print(f"Real-data source: GRB 221009A Box A, ds=1 SEC pair stime={STIME},")
    print(f"  ghost at index {GHOST_FULL} (full cascade {CASCADE_FULL} events).")


if __name__ == "__main__":
    main()
