#!/usr/bin/env python3
"""Fig 3 (wrap_uniqueness): Cross-box validation of grouped-LIS wrap
selection for GRB 221009A, T0+248 to T0+268.

Three curves (all step, for histogram-binned count rates):
  • Box B (orange)      — independent cross-box reference (itself
                          saturated but with FIFO-reset gaps falling at
                          different times from Box A's)
  • Box A wrap j=0 (blue, solid)   — chosen reconstruction; tracks Box B
  • Box A wrap j=1 (blue, dashed)  — alternative reconstruction shifted
                          by exactly the ptime wrap period 1.05 s; the
                          shift is generated by adding +1.05 s post hoc to
                          the j=0 event times, which is equivalent to
                          mis-assigning every event by one wrap

Output: figures/f5_crossbox_recovery.pdf in the paper repo (filename
kept for backwards compatibility with the .tex include path).
"""
import os, sys, subprocess
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pubstyle  # noqa: E402
pubstyle.apply()

EPOCH    = "2022-10-09T13"
TRIGGER  = "2022-10-09T13:17:00"  # unified with the paper T0 (leap-second-aware blink)
BEFORE   = 10.0
AFTER    = 280.0
ZOOM_LO  = 248.0
ZOOM_HI  = 271.5                 # extend past the 1B data end (~T+269.9)
                                 # AND past the +1.05 s-shifted j=1 data end
                                 # (~T+270.95), so the j=1 curve fully
                                 # drops to zero on the right — the wrap
                                 # misalignment is then unambiguous.
BIN      = 0.25                  # 250 ms (Poisson noise ~2% at 10 k evt/s)
WRAP_PERIOD = 1.048576           # seconds
MET_EPOCH = datetime(2012, 1, 1, tzinfo=timezone.utc)


def parse_met(s):
    dt = datetime.strptime(s, "%Y-%m-%dT%H:%M:%S").replace(tzinfo=timezone.utc)
    return (dt - MET_EPOCH).total_seconds()


def run_cli(subcmd, box):
    # current CLI: `sat extract --source 1b` = old `sat <hour> solve`
    # (raw 1B events with MET reconstruction)
    cmd = ["./target/release/blink", "sat", "extract",
           "--before", str(BEFORE), "--after", str(AFTER),
           "--box", box, "--source", "1b", TRIGGER]
    env = os.environ.copy()
    env.setdefault("HXMT_1B_DIR", "data/1B")
    env.setdefault("HXMT_1K_DIR", "data/1K")
    print(f"  $ {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
    mets = []
    for line in proc.stdout.strip().split("\n"):
        parts = line.split(",")
        if len(parts) < 3 or parts[0] == "box":
            continue
        typ, met = parts[1], float(parts[2])
        if typ == "SEC":
            continue
        mets.append(met)
    return np.array(mets)


def main():
    t_ref = parse_met(TRIGGER)

    print("Loading Box A 1B LIS reconstruction...", file=sys.stderr)
    a_evts = run_cli("solve", "a")
    print("Loading Box B 1B LIS reconstruction...", file=sys.stderr)
    b_evts = run_cli("solve", "b")
    print(f"  Box A {len(a_evts):,} events, Box B {len(b_evts):,}",
          file=sys.stderr)

    # Bin (100 ms) over the zoom window
    edges = np.arange(t_ref + ZOOM_LO, t_ref + ZOOM_HI + BIN / 2, BIN)
    x = edges[:-1] - t_ref

    # j=0 = the chosen reconstruction
    a_j0 = a_evts[(a_evts >= edges[0]) & (a_evts < edges[-1])]
    # j=1 = "what if every event were assigned one wrap later"; the visual
    # effect on the binned light curve is identical to a +1.05 s time shift.
    a_j1 = a_evts + WRAP_PERIOD
    a_j1 = a_j1[(a_j1 >= edges[0]) & (a_j1 < edges[-1])]

    b_win = b_evts[(b_evts >= edges[0]) & (b_evts < edges[-1])]

    rate_a0 = np.histogram(a_j0, bins=edges)[0] / BIN
    rate_a1 = np.histogram(a_j1, bins=edges)[0] / BIN
    rate_b  = np.histogram(b_win, bins=edges)[0] / BIN

    fig, ax = plt.subplots(figsize=(pubstyle.COL_W, 2.05))

    # Box B reference (orange)
    ax.step(x, rate_b, where="post", color="#E89028", lw=1.0,
            label="Box B (cross-box reference)", zorder=3)
    # Box A wrap j=0 (blue solid)
    ax.step(x, rate_a0, where="post", color="#1F4E9E", lw=1.0,
            label=r"Box A wrap $j=0$ (chosen)", zorder=4)
    # Box A wrap j=1 (light blue)
    ax.step(x, rate_a1, where="post", color="#7FB0E0", lw=1.0,
            label=r"Box A wrap $j=1$ (alt., $+1.05$ s shift)",
            zorder=2)

    ax.set_xlabel(r"Time $-$ $T_0$ (s)   "
                  f"[bin $=$ {BIN*1000:.0f} ms]")
    ax.set_ylabel("Count rate (counts/s)")
    ax.set_xlim(ZOOM_LO, ZOOM_HI)
    ax.set_ylim(bottom=0)
    ax.grid(alpha=0.18)
    ax.legend(loc="lower center", bbox_to_anchor=(0.60, 0.02))

    plt.tight_layout()
    out_pdf = "/Users/skyair/Developer/ihep/paper-hxmt-saturation/figures/f5_crossbox_recovery.pdf"
    out_png = "/Users/skyair/Developer/ihep/blink/plots/fig3_wrap_uniqueness_preview.png"
    plt.savefig(out_pdf)
    plt.savefig(out_png, dpi=150)
    plt.close()
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")


if __name__ == "__main__":
    main()
